// Tokens.swift — GENERATED by tools/gen-tokens.mjs from app/src/design.js.
// Do not edit. Change design.js and run the generator.
import SwiftUI

struct Palette: Sendable {
    let bg: UInt32
    let surface: UInt32
    let surfaceSunk: UInt32
    let placeholder: UInt32
    let ink: UInt32
    let inkSoft: UInt32
    let inkFaint: UInt32
    let line: UInt32
    let lineStrong: UInt32
    let accent: UInt32
    let accentInk: UInt32
    let good: UInt32
    let warn: UInt32
    let books: UInt32
    let restaurants: UInt32
    let movies: UInt32
    let recipes: UInt32
    let quotes: UInt32
    let places: UInt32
    let wishlist: UInt32
    let notes: UInt32
    let unsorted: UInt32
    let onList: UInt32

    /// A shelf's field colour by its key; unknown keys fall back to `unsorted`.
    func field(_ list: String) -> UInt32 {
        switch list {
        case "books": return books
        case "restaurants": return restaurants
        case "movies": return movies
        case "recipes": return recipes
        case "quotes": return quotes
        case "places": return places
        case "wishlist": return wishlist
        case "notes": return notes
        case "unsorted": return unsorted
        default: return unsorted
        }
    }
}

struct TypeStep: Sendable {
    let size: CGFloat
    let lineHeight: CGFloat
    let tracking: CGFloat
    let weight: Font.Weight
}

enum Tokens {
    static let light = Palette(
        bg: 0xFFFFFF,
        surface: 0xFFFFFF,
        surfaceSunk: 0xF2F2F2,
        placeholder: 0xEAEAEA,
        ink: 0x0A0A0A,
        inkSoft: 0x565656,
        inkFaint: 0x6E6E6E,
        line: 0xDADADA,
        lineStrong: 0x0A0A0A,
        accent: 0xE01000,
        accentInk: 0xFFFFFF,
        good: 0x007A3D,
        warn: 0x8A6100,
        books: 0x0B3EE3,
        restaurants: 0xE01000,
        movies: 0xFFD400,
        recipes: 0x007A3D,
        quotes: 0x6D28D9,
        places: 0xC2410C,
        wishlist: 0xD4107A,
        notes: 0xFFFFFF,
        unsorted: 0x6E6E6E,
        onList: 0xFFFFFF
    )
    static let dark = Palette(
        bg: 0x0A0A0A,
        surface: 0x0A0A0A,
        surfaceSunk: 0x161616,
        placeholder: 0x1E1E1E,
        ink: 0xFFFFFF,
        inkSoft: 0xA8A8A8,
        inkFaint: 0x8A8A8A,
        line: 0x2C2C2C,
        lineStrong: 0xFFFFFF,
        accent: 0xFF5A45,
        accentInk: 0x0A0A0A,
        good: 0x00C462,
        warn: 0xE0B057,
        books: 0x0B3EE3,
        restaurants: 0xE01000,
        movies: 0xFFD400,
        recipes: 0x007A3D,
        quotes: 0x6D28D9,
        places: 0xC2410C,
        wishlist: 0xD4107A,
        notes: 0x0A0A0A,
        unsorted: 0x6E6E6E,
        onList: 0xFFFFFF
    )

    /// Every shelf, in shelf order, with `unsorted` (the pile) last.
    static let listKeys: [String] = ["books", "restaurants", "movies", "recipes", "quotes", "places", "wishlist", "notes", "unsorted"]

    /// The label colour a filled shelf names for itself. A paper shelf (notes)
    /// is not here on purpose: its label is ink. Ask `Theme.on(_:)`.
    static let listOn: [String: UInt32] = ["books": 0xFFFFFF, "restaurants": 0xFFFFFF, "movies": 0x0A0A0A, "recipes": 0xFFFFFF, "quotes": 0xFFFFFF, "places": 0xFFFFFF, "wishlist": 0xFFFFFF, "unsorted": 0xFFFFFF]

    enum Text {
        static let display = TypeStep(size: 36, lineHeight: 42, tracking: -0.45, weight: .bold)
        static let title = TypeStep(size: 25.5, lineHeight: 29.5, tracking: -0.28, weight: .bold)
        static let heading = TypeStep(size: 19.5, lineHeight: 25, tracking: -0.14, weight: .semibold)
        static let read = TypeStep(size: 17, lineHeight: 25, tracking: -0.07, weight: .regular)
        static let body = TypeStep(size: 15, lineHeight: 22, tracking: 0, weight: .regular)
        static let bodyMed = TypeStep(size: 15, lineHeight: 22, tracking: 0, weight: .semibold)
        static let meta = TypeStep(size: 12.5, lineHeight: 17.5, tracking: 0.09, weight: .regular)
        static let micro = TypeStep(size: 11, lineHeight: 15, tracking: 0.48, weight: .semibold)
        static let floor: CGFloat = 11
    }

    enum Space {
        static let xs: CGFloat = 4
        static let sm: CGFloat = 8
        static let md: CGFloat = 12
        static let lg: CGFloat = 16
        static let xl: CGFloat = 24
        static let xxl: CGFloat = 32
        static let huge: CGFloat = 48
    }

    enum Icon {
        static let sm: CGFloat = 18
        static let md: CGFloat = 22
        static let lg: CGFloat = 28
        static let xl: CGFloat = 44
        static let stroke: CGFloat = 1.75
    }

    static let touchMin: CGFloat = 44
    static let touch: CGFloat = 48
    static let board: CGFloat = 7
    static let bandBoard: CGFloat = 6
    static let rule: CGFloat = 3
    static let hairline: CGFloat = 1
    static let coverKeyline: CGFloat = 2

    enum Cover {
        static let minW: CGFloat = 104
        static let heights: [CGFloat] = [156, 164, 172]
        static let comps = 3
        static let pad: CGFloat = 8
        static let jacketGlyph: CGFloat = 0.64
        static let capsGlyph: CGFloat = 0.72
        static let capsTracking: CGFloat = -0.048
        static let quoteGlyph: CGFloat = 0.52
        static let quoteLeading: CGFloat = 1.22
        static let emptyBoardH: CGFloat = 88
        static let maxEmptyBoards = 4
    }

    static let placeholderMix: Double = 0.26

    /// Milliseconds.
    enum Duration {
        static let instant: Double = 90
        static let quick: Double = 150
        static let base: Double = 230
        static let slow: Double = 340
        static let page: Double = 430
    }

    /// Stiffness and damping DERIVED in design.js from a damping ratio and a
    /// settle time; nobody picks a stiffness.
    enum Spring {
        static let press = (stiffness: 985.9, damping: 62.8, mass: 1)
        static let enter = (stiffness: 613.9, damping: 40.6, mass: 1)
        static let sheet = (stiffness: 497.8, damping: 32.1, mass: 1)
    }

    static let staggerStep: Double = 32
    static let staggerMaxSteps = 8
}
