// design.mjs — the golden files for design, serendipity, export and ex-libris,
// and Core/Sources/ShelfCore/DesignConstants.swift.
//
// PARITY IS PROVEN, NOT CLAIMED (swift/PLAN.md, rule 2). This imports the REAL
// modules from app/src, runs them over fixed inputs and writes `{ input,
// output }` cases. The Swift tests run the ports over the same inputs and must
// give the same outputs. Nothing here re-implements a function it checks.
//
// STABLE: no clock, no randomness, the zone is pinned. Two runs give the same
// bytes. Run: `node swift/tools/golden/design.mjs` (from anywhere).
import { writeFileSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import * as D from "../../../app/src/design.js";
import * as S from "../../../app/src/serendipity.js";
import * as E from "../../../app/src/export.js";
import * as X from "../../../app/src/exlibris.js";
import { factsFor } from "../../../app/src/facts.js";

// The selftests pin this zone because it is five and a half hours off UTC, so
// code that confuses local time with UTC cannot pass by luck.
const HOME = "Asia/Kolkata";
const zone = (tz) => {
  process.env.TZ = tz;
  const want = { "Asia/Kolkata": -330, "America/New_York": 240, "Pacific/Auckland": -780, "UTC": 0 }[tz];
  const got = new Date(Date.UTC(2026, 9, 1, 12)).getTimezoneOffset();
  if (got !== want) throw new Error(`the zone pin did not take: ${tz} gave ${got}`);
};
zone(HOME);

const fixtures = fileURLToPath(new URL("../../Core/Tests/ShelfCoreTests/Fixtures/", import.meta.url));
const constantsFile = fileURLToPath(new URL("../../Core/Sources/ShelfCore/DesignConstants.swift", import.meta.url));
mkdirSync(fixtures, { recursive: true });

// A Swift String cannot hold half of a surrogate pair. `excerpt` can cut an
// emoji in two; JS keeps the half, Swift (and every screen) shows U+FFFD. So
// string outputs are written the way a screen shows them.
const well = (v) => (typeof v === "string" ? v.toWellFormed()
  : Array.isArray(v) ? v.map(well)
  : v && typeof v === "object" ? Object.fromEntries(Object.entries(v).map(([k, x]) => [k, well(x)]))
  : v);
// One case per line, so a diff of a golden file shows the case that moved.
const write = (name, blocks) => {
  const body = Object.entries(blocks).map(([k, v]) =>
    Array.isArray(v) ? `${JSON.stringify(k)}: [\n${v.map((c) => JSON.stringify(c)).join(",\n")}\n]` : `${JSON.stringify(k)}: ${JSON.stringify(v)}`);
  writeFileSync(fixtures + name, `{\n${body.join(",\n")}\n}\n`);
  const n = Object.values(blocks).reduce((a, v) => a + (Array.isArray(v) ? v.length : 0), 0);
  console.log(`wrote ${name}: ${n} cases`);
};
const cases = (inputs, fn) => inputs.map((input) => ({ input, output: well(fn(input)) }));

// ═════════════════════════════════════════════════════════════════════════════
// DESIGN
// ═════════════════════════════════════════════════════════════════════════════

const constants = {
  typeFloor: D.TYPE_FLOOR,
  type: Object.fromEntries(Object.values(D.type).map((t) => [t.name, { fontSize: t.fontSize, lineHeight: t.lineHeight, letterSpacing: t.letterSpacing, fontWeight: t.fontWeight }])),
  sp: D.sp,
  board: D.BOARD, rule: D.RULE, hairline: D.HAIRLINE, coverKeyline: D.COVER_KEYLINE,
  coverMinW: D.cover.minW, coverHeights: D.cover.heights, coverComps: D.cover.comps, coverPad: D.cover.pad,
  emptyBoardH: D.EMPTY_BOARD_H, maxEmptyBoards: D.MAX_EMPTY_BOARDS,
  jacketGlyph: D.JACKET_GLYPH, capsGlyph: D.CAPS_GLYPH, capsTracking: D.CAPS_TRACKING,
  quoteGlyph: D.QUOTE_GLYPH, quoteLeading: D.QUOTE_LEADING,
  placeholderMix: D.PLACEHOLDER_MIX,
  staggerStep: D.STAGGER_STEP, staggerMaxSteps: D.STAGGER_MAX_STEPS,
  listKeys: D.LIST_KEYS, listOn: D.listOn, light: D.light, dark: D.dark,
};

const dbl = (n) => (Number.isInteger(n) ? `${n}` : `${n}`);
const strs = (a) => `[${a.map((s) => JSON.stringify(s)).join(", ")}]`;
const dict = (o) => `[\n${Object.entries(o).map(([k, v]) => `        ${JSON.stringify(k)}: ${JSON.stringify(v)},`).join("\n")}\n    ]`;
const c = constants;
const constantsSwift = `// DesignConstants.swift — GENERATED by tools/golden/design.mjs from app/src/design.js.
// Do not edit. Change design.js and run \`node swift/tools/golden/design.mjs\`.
//
// WHY THIS IS NOT Tokens.swift: that file lives in the app target and imports
// SwiftUI, and Core is Foundation only. These are the numbers the FUNCTIONS in
// design.js read (DesignMath.swift), and the palettes as the hex strings
// \`mix\`, \`contrast\` and the export page are written in. Same source, same
// generator rule: never typed by hand. DesignMathTests fails when this file is
// not what the generator writes.
import Foundation

enum DesignConstants {
    struct Step: Sendable, Equatable {
        let fontSize: Double
        let lineHeight: Double
        let letterSpacing: Double
        let fontWeight: String
    }

    static let typeFloor: Double = ${dbl(c.typeFloor)}
${Object.entries(c.type).map(([k, t]) => `    static let ${k} = Step(fontSize: ${dbl(t.fontSize)}, lineHeight: ${dbl(t.lineHeight)}, letterSpacing: ${dbl(t.letterSpacing)}, fontWeight: ${JSON.stringify(t.fontWeight)})`).join("\n")}
    static let type: [String: Step] = [${Object.keys(c.type).map((k) => `${JSON.stringify(k)}: ${k}`).join(", ")}]

    static let sp: [String: Double] = [${Object.entries(c.sp).map(([k, v]) => `${JSON.stringify(k)}: ${dbl(v)}`).join(", ")}]
    enum Space {
${Object.entries(c.sp).map(([k, v]) => `        static let ${k}: Double = ${dbl(v)}`).join("\n")}
    }

    static let board: Double = ${dbl(c.board)}
    static let rule: Double = ${dbl(c.rule)}
    static let hairline: Double = ${dbl(c.hairline)}
    static let coverKeyline: Double = ${dbl(c.coverKeyline)}

    static let coverMinW: Double = ${dbl(c.coverMinW)}
    static let coverHeights: [Double] = [${c.coverHeights.map(dbl).join(", ")}]
    static let coverComps = ${c.coverComps}
    static let coverPad: Double = ${dbl(c.coverPad)}
    static let emptyBoardH: Double = ${dbl(c.emptyBoardH)}
    static let maxEmptyBoards = ${c.maxEmptyBoards}

    static let jacketGlyph: Double = ${dbl(c.jacketGlyph)}
    static let capsGlyph: Double = ${dbl(c.capsGlyph)}
    static let capsTracking: Double = ${dbl(c.capsTracking)}
    static let quoteGlyph: Double = ${dbl(c.quoteGlyph)}
    static let quoteLeading: Double = ${dbl(c.quoteLeading)}

    static let placeholderMix: Double = ${dbl(c.placeholderMix)}
    static let staggerStep: Double = ${dbl(c.staggerStep)}
    static let staggerMaxSteps = ${c.staggerMaxSteps}

    /// Every shelf, in shelf order, with \`unsorted\` (the pile) last.
    static let listKeys: [String] = ${strs(c.listKeys)}
    /// The label colour a filled shelf names for itself. Notes is not here on
    /// purpose: ask \`DesignMath.onFor\`.
    static let listOn: [String: String] = ${dict(c.listOn)}
    static let light: [String: String] = ${dict(c.light)}
    static let dark: [String: String] = ${dict(c.dark)}
}
`;
writeFileSync(constantsFile, constantsSwift);
console.log(`wrote ${constantsFile}`);

const TITLES = [
  "", "A", "It", "Dal", "Piranesi", "The Dispossessed", "Ganapati", "Rosewood", "Sinners", "St. John",
  "Babel, or the Necessity of Violence: An Arcane History of the Oxford Translators' Revolution",
  "Tomorrow, and Tomorrow, and Tomorrow", "The Brothers Karamazov, a novel in four parts", "One, two", "A very long head with no comma in it at all really",
  "Exactly twenty-eight letters!", "Exactly twenty-nine letters!!", "Head , spaced comma that runs well past twenty-eight",
  "Dune: Part Two", "Dune : Part Two", "Dune — Part Two", "Dune—Part Two", "Dune  \t:  Part Two", ": starts with a colon", "— starts with a dash", "   ", " : ",
  "Ends with a colon:", "No:space", "Mission: Impossible — Dead Reckoning", "En–dash is not a split",
  "Supercalifragilisticexpialidocious", "Donaudampfschifffahrtsgesellschaftskapitän", "Llanfairpwllgwyngyllgogerychwyrndrobwllllantysiliogogogoch",
  "Pneumonoultramicroscopicsilicovolcanoconiosis and other words", "a b c d e f g", "mmmmmmmmmmmm", "Twelve chars",
  "Amélie", "Les Misérables", "Čeština a žluťoučký kůň", "Ångström Æther Œuvre", "Café with a combining accent", "İstanbul", "ΟΔΟΣ", "Straße",
  "千と千尋の神隠し", "डाल मखनी", "مرحبا بالعالم",
  "🍜", "Ramen 🍜 night", "👨‍👩‍👧‍👦 family", "🇮🇳 India", "𝒜𝓁𝒾𝒸𝑒 in 𝒲onderland", "😀😀😀😀😀😀😀😀😀😀😀😀😀😀",
  "tab\tseparated\twords", "non breaking space", "line\nbreak here", "em space wide", "zero﻿width nbsp", "next\u0085line is not a space", "mongolian᠎vowel separator",
  "  padded both sides  ", "trailing space ", "double  space", "The trouble with the rat race is that even if you win, you're still a rat.",
  // A head of 27 to 31 characters with a comma in it: only past 28 is it cut.
  ...[27, 28, 29, 30, 31].map((n) => "Head, " + "b".repeat(n - 6)),
  // Only a comma WITH a space after it is a place to cut.
  "Head,nospace and then a comma, with a space after it", "A long head with its only comma at the very end,",
];
const WIDTHS = [104, 105, 107.5, 112, 116, 120, 128, 136, 150, 163.5, 171, 180, 200, 240, 300, 343, 400];
const HEIGHTS = [...D.cover.heights, D.EMPTY_BOARD_H, 20, 200, 320];
const TEXTS = [
  "", " ", "Gift ideas", "milk, eggs, call the plumber", "Brown boots, not black.\nAsk Maya about the scarf.", "Supercalifragilisticexpialidocious", "Gift supercalifragilistic",
  "ab", "abcdefghijkl", "abcdefghijklm", "two words", "exactly twenty-four chars", "exactly twenty-five chars!",
  "The trouble with the rat race is that even if you win, you're still a rat.",
  "It is a truth universally acknowledged, that a single man in possession of a good fortune, must be in want of a wife. However little known the feelings or views of such a man may be on his first entering a neighbourhood, this truth is so well fixed in the minds of the surrounding families.",
  "   leading and trailing whitespace   ", "many     spaces\t\tand\ttabs\n\nand lines", "comma, at the cut; and: more. words follow here, yes; they do: always.",
  "emoji 🍜🍜🍜🍜🍜🍜🍜🍜🍜🍜🍜🍜🍜🍜🍜🍜🍜🍜🍜🍜🍜🍜🍜🍜🍜🍜🍜🍜🍜🍜🍜🍜🍜🍜🍜🍜🍜🍜🍜🍜🍜🍜🍜🍜🍜🍜🍜🍜🍜🍜🍜🍜🍜🍜🍜🍜🍜🍜🍜🍜 in a row",
  "🍜 🍜 🍜 🍜 🍜 🍜 🍜 🍜 🍜 🍜 🍜 🍜 🍜 🍜 🍜 🍜 🍜 🍜 🍜 🍜 🍜 🍜 🍜 🍜 🍜 🍜 🍜 🍜 🍜 🍜 🍜 🍜 🍜 🍜 🍜 🍜 🍜 🍜 🍜 🍜 🍜 🍜 🍜 🍜 🍜 🍜 🍜 🍜",
  "Les Misérables est un roman de Victor Hugo publié en 1862, l'un des plus vastes et des plus célèbres de la littérature française du dix-neuvième siècle.",
  "千と千尋の神隠し 千と千尋の神隠し 千と千尋の神隠し 千と千尋の神隠し 千と千尋の神隠し 千と千尋の神隠し 千と千尋の神隠し 千と千尋の神隠し 千と千尋の神隠し 千と千尋の神隠し",
  "non breaking space is whitespace too", "x".repeat(200), "word ".repeat(60),
];
const HEXES = ["#FFFFFF", "#0A0A0A", "#000000", "#E01000", "#FFD400", "#007A3D", "#0B3EE3", "#6D28D9", "#C2410C", "#D4107A", "#6E6E6E", "#f2f2f2", "#808080", "#0a0B0c", "123456"];
const pairs = HEXES.flatMap((a) => HEXES.map((b) => ({ a, b })));
const PALETTES = { light: D.light, dark: D.dark };
const LISTS = [...D.LIST_KEYS, "gadgets", "", "bg", "ink"];
const perPalette = LISTS.flatMap((list) => Object.keys(PALETTES).map((palette) => ({ list, palette })));
const SPRINGS = [
  { dampingRatio: 1.0, settleMs: 220 }, { dampingRatio: 0.82, settleMs: 340 }, { dampingRatio: 0.72, settleMs: 430 },
  { dampingRatio: 1.4, settleMs: 300 }, { dampingRatio: 0.3, settleMs: 500, mass: 2 }, { dampingRatio: 1.0000000001, settleMs: 220 }, { dampingRatio: 2, settleMs: 90, mass: 0.5 },
];
const TIMES = [-0.1, 0, 1 / 120, 2 / 120, 0.05, 0.1, 0.15, 0.22, 0.34, 0.43, 0.5, 1, 3];

write("golden-design.json", {
  constants,
  constants_swift: constantsSwift,
  coverFor: cases(TITLES.map((title) => ({ title })), ({ title }) => D.coverFor(title)),
  gridFor: cases([-10, 0, 1, 50, 103, 104, 111, 112, 215, 216, 220, 320, 343, 358.5, 375, 390, 400, 430, 744, 1024, 1366]
    .flatMap((available) => [0, 8, 12, 16].map((gap) => ({ available, gap }))), ({ available, gap }) => D.gridFor(available, gap)),
  rowsOf: cases([0, 1, 2, 3, 4, 7, 9, 10].flatMap((n) => [-1, 0, 1, 2, 3, 4].map((cols) => ({ n, cols }))), ({ n, cols }) => D.rowsOf(n, cols)),
  emptyBoards: cases([-5, 0, 568, 667, 812.5, 844, 932, 1366].flatMap((viewportH) => [0, 100, 203, 406, 800, 2000].flatMap((usedH) => [0, -1, 107, 111, 203].map((pitch) => ({ viewportH, usedH, pitch })))),
    ({ viewportH, usedH, pitch }) => D.emptyBoards(viewportH, usedH, pitch)),
  rowPitch: cases([0, 8, 12, 16, 24, 32.5].map((gapAbove) => ({ gapAbove })), ({ gapAbove }) => D.rowPitch(gapAbove)),
  emptyPitch: cases([0, 8, 12, 16, 24, 32.5].map((gapAbove) => ({ gapAbove })), ({ gapAbove }) => D.emptyPitch(gapAbove)),
  mainTitle: cases(TITLES.map((title) => ({ title })), ({ title }) => D.mainTitle(title)),
  jacketType: cases(TITLES.flatMap((title) => [...WIDTHS, 10, 0].map((coverWidth) => ({ title, coverWidth }))), ({ title, coverWidth }) => D.jacketType(title, coverWidth)),
  capsType: cases([D.LIST_KEYS.map((k) => k.toUpperCase()), ["BOOKS"], ["RESTAURANTS", "NOT SHELVED"], [], [""], ["A", "ÉCOLE", "🍜🍜"], TITLES.slice(1, 9)]
    .flatMap((labels) => [40, 96, 128, 163.5, 187, 218, 343, 420].flatMap((boxWidth) => [31, 24, 11, 8].map((max) => ({ labels, boxWidth, max })))),
    ({ labels, boxWidth, max }) => D.capsType(labels, boxWidth, max)),
  quoteType: cases(TEXTS.flatMap((text) => WIDTHS.filter((_, i) => i % 2 === 0).flatMap((coverWidth) => HEIGHTS.map((coverHeight) => ({ text, coverWidth, coverHeight })))),
    ({ text, coverWidth, coverHeight }) => D.quoteType(text, coverWidth, coverHeight)),
  noteType: cases(TEXTS.flatMap((text) => WIDTHS.filter((_, i) => i % 2 === 0).flatMap((coverWidth) => HEIGHTS.map((coverHeight) => ({ text, coverWidth, coverHeight })))),
    ({ text, coverWidth, coverHeight }) => D.noteType(text, coverWidth, coverHeight)),
  excerpt: cases([...TEXTS, ...TITLES].flatMap((text) => [-3, 0, 1, 2, 5, 9, 12, 13, 14, 20, 24, 40, 80, 200, 1000].map((maxChars) => ({ text, maxChars }))), ({ text, maxChars }) => D.excerpt(text, maxChars)),
  mix: cases(pairs.filter((_, i) => i % 3 === 0).flatMap(({ a, b }) => [0, 0.26, 0.5, 0.42, 1].map((t) => ({ a, b, t }))), ({ a, b, t }) => D.mix(a, b, t)),
  luminance: cases(HEXES.map((hex) => ({ hex })), ({ hex }) => D.luminance(hex)),
  contrast: cases(pairs, ({ a, b }) => D.contrast(a, b)),
  isPaper: cases(perPalette, ({ list, palette }) => D.isPaper(list, PALETTES[palette])),
  onFor: cases(perPalette, ({ list, palette }) => D.onFor(list, PALETTES[palette])),
  placeholderOn: cases(perPalette, ({ list, palette }) => D.placeholderOn(list, PALETTES[palette])),
  spring: cases(SPRINGS, (s) => D.spring(s)),
  springAt: cases(SPRINGS.flatMap((spring) => TIMES.map((t) => ({ spring, t }))), ({ spring, t }) => D.springAt(D.spring(spring), t)),
  pressScale: cases([0, 20, 40, 44, 48, 55, 56, 104, 172, 300, 343, 1000].map((sizePt) => ({ sizePt })), ({ sizePt }) => D.pressScale(sizePt)),
  staggerDelay: cases([0, 1, 2, 6, 7, 8, 9, 50].map((i) => ({ i })), ({ i }) => D.staggerDelay(i)),
});

// ═════════════════════════════════════════════════════════════════════════════
// SERENDIPITY
// ═════════════════════════════════════════════════════════════════════════════

const local = (y, m, d, h = 12, min = 0, s = 0, ms = 0) => new Date(y, m - 1, d, h, min, s, ms);
const iso = (...a) => local(...a).toISOString();
// Thursday 1 October 2026 to the Wednesday after, at the minutes where an
// answer changes: midnight, opening, closing, and the small hours.
const INSTANTS = [
  [1, 0, 0], [1, 0, 59], [1, 1, 0], [1, 3, 0], [1, 8, 59], [1, 9, 0], [1, 11, 0], [1, 13, 0], [1, 16, 0], [1, 17, 0], [1, 19, 0], [1, 23, 0], [1, 23, 59],
  [2, 1, 0], [2, 13, 0], [2, 19, 0], [3, 1, 0], [3, 9, 30], [3, 13, 0], [4, 3, 0], [4, 11, 0], [4, 13, 0], [5, 0, 30], [5, 11, 0], [6, 13, 0], [7, 12, 0],
].map(([d, h, m]) => local(2026, 10, d, h, m).getTime());
const HOURS = [
  // what it reads
  "24/7", "  24/7  ", "Mo-Su 00:00-24:00", "Su 00:00-24:00", "Th 00:00-24:00", "Mo-Su 00:00-24:00; We off", "Mo-Su 00:00-24:00,00:00-24:00",
  "Mo-Fr 09:00-17:00; Sa 10:00-16:00", "Mo-Fr 09:00-17:00;Sa 10:00-16:00", "Mo-Fr 09:00-17:00 ; Sa off", "Mo-Fr 09:00-17:00;", ";;Mo-Fr 09:00-17:00;;",
  "Mo-Su 12:00-23:00", "Mo-Su 12:00-23:00; Th off", "Mo-Su 12:00-23:00; Th closed", "Mo,We,Fr 10:00-12:00", "Mo, We, Fr 10:00-12:00", "Fr-Mo 10:00-12:00",
  "Mo-Fr 12:00-15:00,18:00-23:00", "Mo-Fr 12:00-15:00, 18:00-23:00", "Mo-Fr 12:00-15:00,\t18:00-23:00", "12:00-22:00", "Mo-Su 12:00-24:00",
  "Fr-Sa 18:00-02:00", "Fr 18:00-04:00; Sa off", "Mo-Su 18:00-02:00", "Sa-Su 22:00-06:00", "We 22:00-13:30", "Th 13:00-12:59", "Mo 23:00-24:00; Tu 00:00-02:00",
  "Th 12:00-13:00,13:00-14:00", "Th 12:00-13:30,13:00-14:00", "Su-Sa 10:00-11:00", "Mo-Mo 10:00-12:00", "Tu-Mo 10:00-12:00", "Th-We 10:00-12:00",
  "Mo,Tu-Th,Sa 08:00-12:00,13:00-19:00", "Mo-Fr,Su 10:00-22:00", "Mo 10:00-12:00; Mo 14:00-16:00", "Th 10:00-12:00; Th 12:30-16:00",
  "off", "closed", "Mo off", "Mo-Su off", "Th off; Th 09:00-17:00", "Mo-Fr  09:00-17:00", "Mo-Fr\t09:00-17:00", "Mo-Fr 09:00-17:00", "Mo-Fr   09:00-17:00",
  "Su 12:00-16:00; Mo-Sa 09:00-21:00", "Mo-Fr 09:00-17:00; Sa-Su 10:00-02:00", "24:00-02:00", "Th 00:00-00:01", "Th 23:59-24:00", "\n Th 09:00-17:00 \n",
  // THE CEILING: what it must say nothing about
  "Mo-Su 09:00-17:00; PH off", "Mo-Su 00:00-24:00; PH off", "sunrise-sunset", "Mo-Fr 17:00+", "Apr-Oct Mo-Su 10:00-18:00", "week 1-26 Mo-Fr 09:00-17:00",
  "mo-fr 09:00-17:00", "MO 10:00-12:00", 'Mo-Fr 09:00-17:00 || "by appointment"', "Mo-Fr 09:00-17:00, Sa 10:00-14:00", "Mo-Fr 25:00-26:00", "Mo-Fr 09:60-17:00",
  "Mo 10:00-10:00", "Mo 24:00-24:00", "Mo 24:01-25:00", "Mo 00:00-00:00", "Mo-Fr 9-5", "Mo-Fr 9:00-17:00", "open", "", "   ", "24/7; Th off", "24/7 open",
  "Mo-Fr 10:00 - 12:00", "Mo-Fr 10:00–12:00", "Mo-Fr 1000-1200", "Mo-Fr 10:00-12:00 open", "Mo-Fr: 10:00-12:00", "Mo", "Mo ", "Mo-", "Mo- 10:00-12:00",
  ",Mo 10:00-12:00", "Mo,,Tu 10:00-12:00", "Mo-Tu-We 10:00-12:00", "10:00-12:00,", "10:00-12:00,off", "Mo 10:00-12:00 off", "Mo10:00-12:00", "Mo–Fr 09:00-17:00",
  "٠٩:٠٠-١٧:٠٠", "Mo 09:00-17:00\nTu 09:00-17:00", "Mo 09:00-17:00 Tu 09:00-17:00", "Mo-Fr 09:00-17:00; Sa", "off off", "Mo-Su", "Xx 09:00-17:00", "Mo 009:00-17:00",
];
const openCases = HOURS.flatMap((hours) => INSTANTS.map((nowMs) => ({ hours, nowMs, tz: HOME })));
// The same instants read by a phone somewhere else: the answer follows the zone.
const OTHER = ["America/New_York", "Pacific/Auckland", "UTC"];
const openElsewhere = OTHER.flatMap((tz) => HOURS.slice(0, 12).flatMap((hours) => INSTANTS.filter((_, i) => i % 4 === 0).map((nowMs) => ({ hours, nowMs, tz }))));
const runOpen = (list) => list.map((input) => { zone(input.tz); const out = { input, output: S.openState(input.hours, new Date(input.nowMs)) }; return out; });
const openState = [...runOpen(openCases), ...runOpen(openElsewhere)];
zone(HOME);

const STJOHN = { lat: 51.5203, lng: -0.1027 };
const HERE = { lat: STJOHN.lat - 400 / 111195, lng: STJOHN.lng };
const north = (m) => ({ lat: HERE.lat + m / 111195, lng: HERE.lng });
const POINTS = [STJOHN, HERE, north(4), north(990), north(1000), north(1001), { lat: 0, lng: 0 }, { lat: -33.8688, lng: 151.2093 }, { lat: 89.9, lng: 179.9 }, { lat: -89.9, lng: -179.9 }, { lat: 12.9716, lng: 77.5946 }, null];
const metresBetween = cases(POINTS.flatMap((a) => POINTS.map((b) => ({ a, b }))), ({ a, b }) => S.metresBetween(a, b));

const item = (id, list, title, created_at, extra = {}) => ({ id, list, status: "filed", title, subtitle: "", note: "", canonical: {}, created_at, ...extra });
const NOW = local(2026, 10, 1, 13);
const at = (y, m, d, h = 12) => iso(y, m, d, h);
const ALL = [
  item("book", "books", "Piranesi", at(2025, 10, 1)),
  item("film", "movies", "Sinners", at(2024, 10, 3)),
  item("dal", "recipes", "Dal", at(2026, 1, 10)),
  item("quote", "quotes", "The trouble with the rat race", at(2026, 2, 1)),
  item("loose", "unsorted", "A thing", at(2025, 12, 1)),
  item("stjohn", "restaurants", "St. John", at(2026, 9, 20), { note: "bone marrow", canonical: { ...STJOHN, city: "London", opening_hours: "Mo-Sa 12:00-23:00" } }),
  item("bookbar", "places", "Book Bar", at(2026, 5, 1), { canonical: north(150) }),
  item("holiday", "restaurants", "Holiday Cafe", at(2026, 9, 25), { note: "x", canonical: { ...north(200), opening_hours: "Mo-Su 09:00-17:00; PH off" } }),
  item("shut", "restaurants", "Early Week", at(2026, 9, 25), { note: "x", canonical: { ...north(100), opening_hours: "Mo-We 09:00-17:00" } }),
  item("peckham", "places", "Multi Story", at(2026, 3, 1), { canonical: { lat: 51.47, lng: -0.07 } }),
  item("noted", "books", "Babel", at(2025, 1, 5), { note: "read this twice" }),
  item("fresh", "movies", "New Film", at(2026, 9, 28)),
  { ...item("pending", "unsorted", null, at(2025, 10, 1)), status: "pending" },
  { ...item("unread", "unsorted", null, at(2025, 10, 1)), status: "unread", canonical: north(50) },
  item("shirt", "wishlist", "Wool overshirt", at(2026, 9, 29), { canonical: { kind: "product", brand: "Northfield" } }),
  item("jot", "notes", "Ask Maya about the scarf", at(2026, 9, 29), { note: "Ask Maya about the scarf", canonical: { kind: "note" } }),
];
for (const k of D.LIST_KEYS) if (!ALL.some((i) => i.list === k)) throw new Error(`the fixtures have nothing on ${k}`);

const NEAR = [
  item("a-open", "restaurants", "Open far", at(2026, 9, 1), { canonical: { ...north(700), opening_hours: "Mo-Su 09:00-22:00" } }),
  item("b-open", "restaurants", "Open near", at(2026, 9, 1), { canonical: { ...north(60), opening_hours: "Mo-Su 18:00-02:00" } }),
  item("c-247", "places", "Always", at(2026, 9, 1), { canonical: { ...north(250), opening_hours: "24/7" } }),
  item("d-none", "places", "No hours", at(2026, 9, 1), { canonical: north(330) }),
  item("e-junk", "places", "Junk hours", at(2026, 9, 1), { canonical: { ...north(20), opening_hours: "sunrise-sunset" } }),
  item("f-shut", "restaurants", "Shut", at(2026, 9, 1), { canonical: { ...north(10), opening_hours: "Mo-We 09:00-17:00" } }),
  item("g-edge", "places", "Exactly a walk", at(2026, 9, 1), { canonical: north(1000 - 0.001) }),
  item("h-far", "places", "Past a walk", at(2026, 9, 1), { canonical: north(1000.5) }),
  item("i-here", "places", "Right here", at(2026, 9, 1), { canonical: { ...HERE, opening_hours: "Mo-Su 00:00-24:00" } }),
  item("j-tie1", "places", "Tie one", at(2026, 9, 1), { canonical: north(500) }),
  item("j-tie2", "places", "Tie two", at(2026, 9, 1), { canonical: north(500) }),
  // A pin that is not two numbers is no pin, and hours that are not a string
  // are read the way JS reads them: String(value).
  item("k-str", "places", "String pin", at(2026, 9, 1), { canonical: { lat: String(north(40).lat), lng: String(HERE.lng) } }),
  item("l-half", "places", "Half pin", at(2026, 9, 1), { canonical: { lat: north(40).lat, lng: null } }),
  item("m-arr", "places", "Hours in an array", at(2026, 9, 1), { canonical: { ...north(440), opening_hours: ["Mo-Su 09:00-22:00"] } }),
  item("n-num", "places", "Hours as a number", at(2026, 9, 1), { canonical: { ...north(445), opening_hours: 247 } }),
  item("o-null", "places", "Hours null", at(2026, 9, 1), { canonical: { ...north(450), opening_hours: null } }),
  item("p-two", "places", "Two rules in an array", at(2026, 9, 1), { canonical: { ...north(455), opening_hours: ["Mo-Su 09:00-12:00", "13:00-22:00"] } }),
];
const YEARS = [
  item("y1-now", "books", "x", NOW.toISOString().replace("2026", "2025")),
  item("y2-day", "books", "x", at(2024, 10, 1, 9)),
  item("y3-day", "books", "x", at(2023, 10, 1, 23)),
  item("y4", "books", "x", at(2022, 10, 1), { note: "n" }),
  item("y1-edge-in", "books", "x", new Date(local(2025, 10, 1, 13).getTime() - 3.5 * 86400000).toISOString(), { note: "n" }),
  item("y1-edge-out", "books", "x", new Date(local(2025, 10, 1, 13).getTime() - 3.5 * 86400000 - 1).toISOString(), { note: "n" }),
  item("y1-edge-in2", "books", "x", new Date(local(2025, 10, 1, 13).getTime() + 3.5 * 86400000).toISOString(), { note: "n" }),
  item("y1-edge-out2", "books", "x", new Date(local(2025, 10, 1, 13).getTime() + 3.5 * 86400000 + 1).toISOString(), { note: "n" }),
  item("y1-yesterday", "books", "x", at(2025, 9, 30, 23), { note: "n" }),
  item("y1-late", "books", "x", iso(2025, 10, 1, 23, 59, 59, 999), { note: "n" }),
  item("y1-early", "books", "x", iso(2025, 10, 1, 0, 0, 0, 0), { note: "n" }),
  item("y-bad", "books", "x", "nope"),
  item("y-empty", "books", "x", ""),
  item("y-dateonly", "books", "x", "2025-10-01"),
  item("y-localform", "books", "x", "2025-10-01T13:00:00"),
  item("y-offset", "books", "x", "2025-10-02T01:00:00.250+05:30"),
];
// 29 February has no anniversary in a common year: setFullYear rolls to 1 March.
const LEAP = [item("leap", "books", "x", iso(2024, 2, 29, 10)), item("leap2", "books", "x", iso(2024, 2, 28, 10))];
// The same minute, so the id decides — in the order `localeCompare` gives.
const TIES = ["b", "a", "B", "A", "10", "2", "_x", "-x", "é", "e", "z", "Z", "i_k3j2", "i_K3J2", "ä", "a b", "ab", "aB", "Ab"].map((id) => item(id, "books", id, at(2025, 12, 1)));
const FORGOT = [
  item("f-90", "books", "x", new Date(NOW.getTime() - 90 * 86400000).toISOString()),
  item("f-89", "books", "x", new Date(NOW.getTime() - 90 * 86400000 + 1).toISOString()),
  item("f-space", "books", "x", at(2026, 1, 1), { note: " \n\t  " }),
  item("f-note", "books", "x", at(2026, 1, 1), { note: " . " }),
  item("f-dec", "books", "x", iso(2025, 12, 31, 23, 59)),
  item("f-jan", "books", "x", iso(2026, 1, 1, 0, 0)),
];
const JUNK = [{}, { status: "filed" }, { id: "x", status: "filed", created_at: "nope" }, { id: "", status: "filed", created_at: at(2025, 10, 1) },
  { id: "bare", status: "filed", created_at: at(2025, 10, 1) }, { id: "dup", status: "filed", created_at: at(2025, 10, 1), list: "books" },
  { id: "dup", status: "filed", created_at: at(2024, 10, 1), list: "books" }, { id: "st", status: "nope", created_at: at(2025, 10, 1) }];

const surfaceInputs = [];
const push = (name, items, opts, tz = HOME) => surfaceInputs.push({ name, items, nowMs: opts.now.getTime(), here: opts.here ?? null, limit: opts.limit ?? null, seen: opts.seen ?? null, tz });
push("all, here", ALL, { now: NOW, here: HERE, limit: 99 });
push("all, no place", ALL, { now: NOW, limit: 99 });
push("all, defaults", ALL, { now: NOW, here: HERE });
for (const limit of [0, 1, 2, 5, -1]) push(`limit ${limit}`, ALL, { now: NOW, here: HERE, limit });
push("seen", ALL, { now: NOW, here: HERE, limit: 99, seen: ["stjohn", "book"] });
push("seen everything near", ALL, { now: NOW, here: HERE, limit: 99, seen: ["stjohn", "bookbar", "holiday", "shut", "nobody"] });
push("a place that is two strings", ALL, { now: NOW, here: { lat: String(HERE.lat), lng: String(HERE.lng) }, limit: 99 });
push("a place far from everything", ALL, { now: NOW, here: { lat: 12.9716, lng: 77.5946 }, limit: 99 });
// The pile turns once a day, at the phone's midnight.
for (let d = 0; d < 14; d++) push(`day ${d}`, ALL, { now: local(2026, 10, 1 + d, 13), limit: 99, seen: ["book", "film"] });
for (const [h, m, s, ms] of [[0, 0, 0, 0], [2, 0, 0, 0], [5, 29, 59, 999], [5, 30, 0, 0], [22, 0, 0, 0], [23, 59, 59, 999]]) push(`the hour ${h}:${m}`, ALL, { now: local(2026, 10, 1, h, m, s, ms), here: HERE, limit: 99 });
for (const [d, h, m] of [[1, 9, 0], [1, 17, 59], [1, 22, 0], [2, 1, 30], [2, 2, 0], [4, 13, 0], [5, 3, 0]]) push(`near at ${d} ${h}:${m}`, NEAR, { now: local(2026, 10, d, h, m), here: HERE, limit: 99 });
push("years", YEARS, { now: NOW, limit: 99 });
push("years, an hour later", YEARS, { now: local(2026, 10, 1, 14), limit: 99 });
push("years, just before midnight", YEARS, { now: local(2026, 10, 1, 23, 59), limit: 99 });
push("years, just after midnight", YEARS, { now: local(2026, 10, 2, 0, 1), limit: 99 });
push("leap, 28 Feb", LEAP, { now: local(2025, 2, 28, 10), limit: 99 });
push("leap, 1 Mar", LEAP, { now: local(2025, 3, 1, 10), limit: 99 });
push("leap, 29 Feb four years on", LEAP, { now: local(2028, 2, 29, 10), limit: 99 });
for (let d = 0; d < 5; d++) push(`ties ${d}`, TIES, { now: local(2026, 10, 1 + d, 13), limit: 99 });
push("ninety days", FORGOT, { now: NOW, limit: 99 });
push("junk rows", JUNK, { now: NOW, here: HERE, limit: 99 });
push("nothing", [], { now: NOW, here: HERE });
push("triple", [item("triple", "restaurants", "Triple", at(2025, 10, 1), { canonical: north(300) })], { now: NOW, here: HERE, limit: 99 });
// THE ZONE IS AN ARGUMENT. The same shelf and the same instant, read by a
// phone somewhere else, is a different local day and a different card.
for (const tz of OTHER) {
  push(`all in ${tz}`, ALL, { now: NOW, here: HERE, limit: 99 }, tz);
  push(`years in ${tz}`, YEARS, { now: NOW, limit: 99 }, tz);
  for (let d = 0; d < 3; d++) push(`ties ${d} in ${tz}`, TIES, { now: new Date(NOW.getTime() + d * 86400000 + 9 * 3600000), limit: 99 }, tz);
  push(`near in ${tz}`, NEAR, { now: local(2026, 10, 2, 1, 30), here: HERE, limit: 99 }, tz);
}
// A local time that does not exist, and one that happens twice (New York).
// `setFullYear` has to pick the same instant JS picks, and the 3.5-day edge is
// placed so the other choice, an hour away, falls outside it.
{
  zone("America/New_York");
  const gap = new Date(2025, 2, 8, 2, 30);          // 02:30 on 8 March 2026 does not exist
  const gapDue = new Date(gap); gapDue.setFullYear(2026);
  const twice = new Date(2024, 10, 1, 1, 30);       // 01:30 on 1 November 2026 happens twice
  const twiceDue = new Date(twice); twiceDue.setFullYear(2026);
  for (const sign of [1, -1]) {
    push(`spring forward ${sign}`, [item("gap", "books", "x", gap.toISOString(), { note: "n" })], { now: new Date(gapDue.getTime() + sign * 3.5 * 86400000), limit: 99 }, "America/New_York");
    push(`fall back ${sign}`, [item("twice", "books", "x", twice.toISOString(), { note: "n" })], { now: new Date(twiceDue.getTime() + sign * 3.5 * 86400000), limit: 99 }, "America/New_York");
  }
  zone(HOME);
}
const surface = surfaceInputs.map((input) => {
  zone(input.tz);
  const opts = { now: new Date(input.nowMs) };
  if (input.here) opts.here = input.here;
  if (input.limit !== null) opts.limit = input.limit;
  if (input.seen) opts.seen = input.seen;
  const output = S.surface(input.items, opts).map((card) => ({ kind: card.kind, id: card.item.id, reason: card.reason, action: card.action ?? null }));
  return { input, output };
});
zone(HOME);

// What `new Date(string)` makes of a string, because both ports read
// `created_at` through it. Swift reads the ISO forms; the rest are listed in
// the Swift test as known differences, by name.
const DATE_STRINGS = [
  "2026-10-01T07:30:00.000Z", "2026-10-01", "2026-10", "2026", "2026-10-01T12:00", "2026-10-01T12:00:00", "2026-10-01T12:00:00.5", "2026-10-01T12:00:00.123456Z",
  "2026-10-01T12:00:00+05:30", "2026-10-01T12:00:00-08:00", "2026-10-01T12:00:00-00:00", "2026-10-01T12:00Z", "2026-10-01t12:00:00z", "2026-10-01T07:30:00.000z",
  "2026-10-01T12:00:00.9999Z", "2026-10-01T12:00:00.9Z", "2026-10-01T12:00:00.09Z", "2026-10-01T23:59:59.999", "2026-10-01T00:00", "2026-10T12:00", "2026T12:00", "2026T12:00Z",
  "2026-10-01Z", "2026-10Z", "2026Z", "2026-10-01+05:30", "2024-02-29T10:00:00Z", "2025-02-29T10:00:00Z", "2026-02-30", "2026-02-30T00:00:00Z", "2026-02-31", "2026-04-31", "2026-04-31T10:00",
  "2026-10-01T24:00:00Z", "2026-10-01T24:00", "2026-10-01T24:00:00.000", "2026-10-01T24:00:01Z", "2026-10-01T24:01Z", "2026-10-01T25:00:00Z", "0000-01-01T00:00:00Z", "0001-01-01", "1969-12-31T23:59:59.999Z", "9999-12-31T23:59:59.999Z",
  "2026-13-01", "2026-00-10", "2026-10-00", "2026-10-32", "2026-10-01T12:60:00Z", "2026-10-01T12:00:60Z", "2026-10-01T12:00:00+24:00", "2026-10-01T12:00:00+23:59", "2026-10-01T12:00:00+05:60",
  "2026-10-01T12:00:00Zjunk", "2026-10-01T", "2026-10-01T12Z", "2026-10-01T12", "2026-10-01T12:00:00.Z", "2026-10-01T12:00:00,5Z", "20261001", " 2026-10-01T07:30:00.000Z", "2026-10-01T07:30:00.000Z ",
  "nope", "", "null", "0", "2026-10-01T12:00:00+5:30", "2026-10-01T12:00:00+05", "2026-10-01T1:00", "202-10-01", "2026-1-01T00:00:00Z", "２０２６-10-01",
  // read by V8's older, looser parser and by nothing in Swift
  "2026-10-01 12:00:00", "2026-10-01T12:00:00+0530", "2026-1-1", "Oct 1 2026", "1 October 2026 13:00", "Thu, 01 Oct 2026 07:30:00 GMT", "10/01/2026", "+002026-10-01T00:00:00Z", "2026-10-01T12:00:00 Z",
];
const dates = [HOME, "America/New_York"].flatMap((tz) => DATE_STRINGS.map((text) => {
  zone(tz);
  const t = new Date(text).getTime();
  return { input: { text, tz }, output: Number.isNaN(t) ? null : t };
}));
zone(HOME);

write("golden-serendipity.json", { metresBetween, openState, surface, dates });

// ═════════════════════════════════════════════════════════════════════════════
// EXPORT
// ═════════════════════════════════════════════════════════════════════════════

// A WHOLE item, with every key the app writes, so the Swift model writes back
// exactly the keys it read and the two JSON files are equal key for key.
const whole = (id, list, title, extra = {}) => ({
  id, list, status: "filed", title, subtitle: "", note: "", image_url: null, canonical: {},
  confidence: 0.9, enriched: true, source_url: null, resolver: "test", created_at: iso(2026, 3, 2, 12), resolved_at: iso(2026, 3, 2, 12, 1), ...extra,
});
// The selftest's shape: no `resolved_at`, and the optional keys present but
// empty. The Swift model adds the first and drops the others; the Swift test
// pins exactly that and nothing more.
const thin = (id, list, title, extra = {}) => {
  const { resolved_at, ...rest } = whole(id, list, title, extra);
  return rest;
};
const ARTICLE = "First paragraph of the saved piece.\n\nSecond paragraph, which outlives the link.";
const mainItems = (mk) => [
  mk("b1", "books", "Piranesi", { subtitle: "Susanna Clarke · 2020", note: "The House is <b>kind</b> & vast",
    image_url: "https://covers.example/piranesi.jpg", source_url: "https://www.instagram.com/reel/abc/",
    caption: "5 books I read this month", top: true, future_key: { a: 1, b: [true, null, "x"] },
    canonical: { author: "Susanna Clarke", year: 2020, pages: 272, rating: 4.5, first_sentence: "When the Moon rose", subjects: ["Fantasy", "Labyrinths"], read_url: "https://openlibrary.org/works/OL1W" } }),
  mk("r1", "restaurants", "St. John", { canonical: { lat: 51.5203, lng: -0.1027, city: "London", address: "26 St John St",
    opening_hours: "Mo-Sa 12:00-23:00", cuisine: ["British"], website: "https://stjohnrestaurant.com", phone: "+44 20 7251 0848" } }),
  mk("m1", "movies", "Sinners", { canonical: { runtime_min: 137, rating: 7.6, overview: "Twin brothers return home.", genres: ["Horror", "Drama"], cast: ["Michael B. Jordan"], streaming: ["Mubi", "Netflix"], watch_url: "https://watch.example/sinners", trailer_url: "HTTPS://Video.example/t" } }),
  mk("c1", "recipes", "Dal", { canonical: { total_time: "40 min", serves: "4", steps: 6, ingredients: ["lentils", "", "ghee"], recipe_url: "https://food.example/dal" } }),
  mk("q1", "quotes", "The trouble with the rat race is that even if you win, you're still a rat.", { canonical: { author: "Lily Tomlin" } }),
  mk("p1", "places", "Book Bar", { canonical: { city: "London", area: "Islington", located: false } }),
  mk("w1", "wishlist", "Wool overshirt", { canonical: { kind: "product", price: 65, currency: "GBP", price_text: "£65.00",
    brand: "Northfield", availability: "in_stock", shop_url: "https://shop.example/overshirt" } }),
  mk("n1", "notes", "Brown boots, not black.", { note: "  Brown boots, not black.\nAsk Maya about the scarf.  ", canonical: { kind: "note" } }),
  mk("a1", "unsorted", "A long read", { source_url: "  https://example.com/long-read  ",
    canonical: { article: { text: `\n${ARTICLE}\n`, byline: "A. Writer", siteName: "The Paper" }, ocr_text: "words read off a screenshot" } }),
  mk("a2", "unsorted", "Plain text", { canonical: { article: "just the text" } }),
  mk("a3", "unsorted", "Blank text", { canonical: { article: { text: "   ", byline: "Nobody" } } }),
  mk("a4", "unsorted", "Half a byline", { canonical: { article: { text: "words", siteName: "The Paper" } } }),
  mk("g1", "gadgets", "On a shelf that does not exist", { created_at: "nope" }),
  mk("e1", "books", "", { subtitle: "An empty title is Untitled" }),
  { ...mk("u1", "unsorted", null, { source_url: "https://www.instagram.com/reel/zzz/", created_at: iso(2026, 9, 30, 23, 45) }), status: "unread", error: "could not read it" },
  { ...mk("u2", "unsorted", null, { created_at: iso(2026, 10, 1, 0, 15) }), status: "pending" },
];
const PROFILE = { name: "Suren", bio: "Reads on trains", seed: "suren", home_city: "London" };
const LINKS = [
  { code: "k7m2pq9x", kind: "shelf", target: "books", title: "Books", at: iso(2026, 9, 1, 12), revoke_secret: "s3cr3t-token" },
  { code: "zz11yy22", kind: "card", target: null, title: "Suren", at: iso(2026, 9, 2, 12) },
];
const BOARDS = [
  { id: "l1", name: "Autumn outfit", pins: ["w1", "n1"], query: null, view: "pictures", created_at: iso(2026, 9, 3, 12) },
  { id: "l2", name: "London", pins: [], query: "london", view: "rows", created_at: "" },
];
const XSS = `"><script>alert(1)</script><img src=x onerror=alert(2)>`;
const nasty = {
  version: 1,
  profile: { name: XSS, bio: XSS, seed: XSS, home_city: XSS },
  items: [
    whole("n1", "books", XSS, { subtitle: XSS, note: XSS, image_url: "https://img.example/a.jpg",
      canonical: { author: XSS, first_sentence: XSS, subjects: [XSS], article: { text: XSS, byline: XSS, siteName: XSS } } }),
    whole("n2", "restaurants", "Cafe", { canonical: { address: XSS, opening_hours: XSS, cuisine: [XSS], phone: XSS, website: `https://x.example/${XSS}` } }),
    whole("n3", "movies", "Film", { canonical: { overview: XSS, genres: [XSS], cast: [XSS], streaming: [XSS], watch_url: "https://watch.example/" } }),
    whole("n4", "gadgets<script>", XSS, { status: XSS, created_at: XSS }),
    whole("n5", "books", "T", { image_url: `https://x.example/a.jpg"onerror="alert(1)`, source_url: `https://x.example/?a="><script>`, canonical: { read_url: `https://x.example/"onmouseover="alert(1)` } }),
    whole("n6", "books", "It's & <ok>", { subtitle: "'single' \"double\"", source_url: "http://plain.example/" }),
  ],
  links: [], boards: [],
};
const BAD_URLS = ["javascript:alert(1)", "JaVaScRiPt:alert(1)", " javascript:alert(1)", "javascript:alert('https://ok.example/')", "data:text/html,<script>x</script>",
  "file:///etc/passwd", "vbscript:x", "//evil.example/x", "geo:51.5,-0.1", "https://ok.example/a b", "https://", "http://", "https://ok.example/a b", "ftp://x.example/", "", "TEL:+44 20", "tel:+44 20 7251"];
const urls = {
  version: 1, profile: { name: "", bio: "", seed: "", home_city: "" }, links: [], boards: [],
  items: BAD_URLS.flatMap((url, i) => [
    whole(`u${i}`, "recipes", "T", { image_url: url, source_url: url, canonical: { recipe_url: url } }),
    whole(`v${i}`, "books", "B", { canonical: { read_url: url } }),
    whole(`w${i}`, "movies", "M", { canonical: { trailer_url: url, watch_url: url } }),
    whole(`x${i}`, "restaurants", "R", { canonical: { website: url, phone: url } }),
  ]),
};
const SHELVES = [
  { name: "main", shelf: { version: 1, items: mainItems(whole), profile: PROFILE, links: LINKS, boards: BOARDS }, now: NOW, tz: HOME, strict: true },
  { name: "the selftest's thin items", shelf: { version: 1, items: mainItems(thin).map((i) => ({ ...i, caption: i.caption ?? null, error: i.error ?? null, top: i.top ?? false })), profile: PROFILE, links: LINKS, boards: BOARDS }, now: NOW, tz: HOME, strict: false },
  // One item here has a status that is not a status. JS exports the string;
  // the Swift model has already read it as `unread`.
  { name: "nasty", shelf: nasty, now: NOW, tz: HOME, strict: false },
  { name: "urls", shelf: urls, now: NOW, tz: HOME, strict: true },
  { name: "empty", shelf: { version: 1, items: [], profile: { name: "", bio: "", seed: "", home_city: "" }, links: [], boards: [] }, now: NOW, tz: HOME, strict: true },
  { name: "one thing, nobody's", shelf: { version: 1, items: [whole("only", "movies", "Sinners")], profile: { name: "", bio: "Bio with no name", seed: "", home_city: "" }, links: [], boards: [] }, now: NOW, tz: HOME, strict: true },
  { name: "no clock", shelf: { version: 1, items: mainItems(whole), profile: PROFILE, links: LINKS, boards: BOARDS }, now: null, tz: HOME, strict: true },
  // 13:00 in Kolkata on the 1st is 03:30 in New York on the 1st, and 23:45 on
  // 30 September in Kolkata is still the 30th there: the days on the page move.
  { name: "main, in New York", shelf: { version: 1, items: mainItems(whole), profile: PROFILE, links: LINKS, boards: BOARDS }, now: local(2026, 10, 1, 4), tz: "America/New_York", strict: true },
  { name: "main, in Auckland", shelf: { version: 1, items: mainItems(whole), profile: PROFILE, links: LINKS, boards: BOARDS }, now: local(2026, 12, 31, 23, 59), tz: "Pacific/Auckland", strict: true },
];
const exportCases = SHELVES.map(({ name, shelf, now, tz, strict }) => {
  zone(tz);
  const ids = shelf.items.map((i) => i.id);
  if (new Set(ids).size !== ids.length) throw new Error(`${name}: the Swift test finds facts by id, so ids must differ`);
  const facts = Object.fromEntries(shelf.items.map((i) => [i.id, factsFor({ ...i, canonical: i.canonical && typeof i.canonical === "object" ? i.canonical : {} }, { platform: null })]));
  const opts = now ? { now } : {};
  return { name, input: { shelf, nowMs: now ? now.getTime() : null, tz, strict }, facts, output: { json: E.exportJson(shelf, opts), html: E.exportHtml(shelf, opts) } };
});
zone(HOME);
const filenames = [HOME, "America/New_York", "Pacific/Auckland", "UTC"].flatMap((tz) => {
  zone(tz);
  return [NOW.getTime(), Date.UTC(2026, 0, 4, 19, 0), Date.UTC(2026, 11, 31, 23, 59, 59), Date.UTC(999, 0, 1, 12), null]
    .flatMap((nowMs) => ["json", "html", "../../etc/passwd", "HTML", ""].map((kind) => ({ input: { kind, nowMs, tz }, output: E.exportFilename(kind, nowMs === null ? null : new Date(nowMs)) })));
});
zone(HOME);
const esc = cases([`<a href="x" title='y'>&`, "", "plain", XSS, "&amp;", "a & b < c > d \" e ' f", "“curly” · dots…", "🍜 <b>", "'''", "&&&", "line\nbreak\ttab"].map((text) => ({ text })), ({ text }) => E.esc(text));
write("golden-export.json", { format: E.EXPORT_FORMAT, version: E.EXPORT_VERSION, export: exportCases, filename: filenames, esc });

// ═════════════════════════════════════════════════════════════════════════════
// EX LIBRIS
// ═════════════════════════════════════════════════════════════════════════════

const HANDLES = [
  "", "suren", "nadia", "Suren", "SUREN", "a", "A", "z", "ab", "maya", "lily", "piranesi", "book_bar", "_x", "9lives", "@suren", " spaced ", "x y", "!!!", "?", "-", "0",
  "José", "josé", "JOSÉ", "ΟΔΟΣ", "οδος", "Σ", "ΑΣ ΑΣ", "İstanbul", "istanbul", "ISTANBUL", "ıstanbul", "Straße", "STRASSE", "日本語", "千と千尋", "डाल", "مرحبا", "Ñandú",
  "😀", "😀emoji", "a😀b", "𝒜lice", "👨‍👩‍👧‍👦", "é", "é", "ǅ", "ﬁsh", "a".repeat(64), "The Quick Brown Fox", "user@example.com", "o'neil", "anne-marie", "x_1", "1x", "q", "Qq", "qQ", "QQ",
  ...Array.from({ length: 80 }, (_, i) => `user${i}`),
];
write("golden-exlibris.json", {
  constants: { plate: X.PLATE, grounds: X.GROUNDS, borders: X.BORDERS, devices: X.DEVICES, roles: X.ROLES },
  plate: cases(HANDLES.map((handle) => ({ handle })), ({ handle }) => ({
    plate: X.plateFor(handle),
    light: X.plateColours(handle, D.light),
    dark: X.plateColours(handle, D.dark),
    shapes: X.plateShapes(handle),
  })),
});
