// gen-tokens.mjs — Sources/Design/Tokens.swift, written from app/src/design.js.
//
// GENERATED, NEVER HAND-COPIED. design.js is the one palette and the one type
// scale; the Expo app, the server's pages and this Swift app all read it. A
// Swift file typed out by hand would agree today and drift the first time a
// step moves. Run: `node tools/gen-tokens.mjs` (also checked by the tests,
// which fail when the committed file is stale).
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import * as D from "../../app/src/design.js";

const out = fileURLToPath(new URL("../Sources/Design/Tokens.swift", import.meta.url));
const hex = (h) => `0x${h.replace("#", "").toUpperCase()}`;
const num = (n) => (Number.isInteger(n) ? `${n}` : `${n}`);
const palette = (name, p) => `    static let ${name} = Palette(\n` +
  Object.entries(p).map(([k, v]) => `        ${k}: ${hex(v)}`).join(",\n") + "\n    )";
const weight = (w) => ({ "400": ".regular", "600": ".semibold", "700": ".bold" }[String(w)] ?? ".regular");

const swift = `// Tokens.swift — GENERATED by tools/gen-tokens.mjs from app/src/design.js.
// Do not edit. Change design.js and run the generator.
import SwiftUI

struct Palette: Sendable {
${Object.keys(D.light).map((k) => `    let ${k}: UInt32`).join("\n")}

    /// A shelf's field colour by its key; unknown keys fall back to \`unsorted\`.
    func field(_ list: String) -> UInt32 {
        switch list {
${D.LIST_KEYS.map((k) => `        case "${k}": return ${k}`).join("\n")}
        default: return unsorted
        }
    }
}

struct TypeStep: Sendable {
    let size: CGFloat
    let lineHeight: CGFloat
    let tracking: CGFloat
    let weight: Font.Weight
}

enum Tokens {
${palette("light", D.light)}
${palette("dark", D.dark)}

    /// Every shelf, in shelf order, with \`unsorted\` (the pile) last.
    static let listKeys: [String] = [${D.LIST_KEYS.map((k) => `"${k}"`).join(", ")}]

    /// The label colour a filled shelf names for itself. A paper shelf (notes)
    /// is not here on purpose: its label is ink. Ask \`Theme.on(_:)\`.
    static let listOn: [String: UInt32] = [${Object.entries(D.listOn).map(([k, v]) => `"${k}": ${hex(v)}`).join(", ")}]

    enum Text {
${Object.values(D.type).map((t) => `        static let ${t.name} = TypeStep(size: ${num(t.fontSize)}, lineHeight: ${num(t.lineHeight)}, tracking: ${num(t.letterSpacing)}, weight: ${weight(t.fontWeight)})`).join("\n")}
        static let floor: CGFloat = ${D.TYPE_FLOOR}
    }

    enum Space {
${Object.entries(D.sp).map(([k, v]) => `        static let ${k}: CGFloat = ${v}`).join("\n")}
    }

    enum Icon {
${Object.entries(D.icon).map(([k, v]) => `        static let ${k}: CGFloat = ${v}`).join("\n")}
        static let stroke: CGFloat = ${D.STROKE}
    }

    static let touchMin: CGFloat = ${D.TOUCH_MIN}
    static let touch: CGFloat = ${D.TOUCH}
    static let board: CGFloat = ${D.BOARD}
    static let bandBoard: CGFloat = ${D.BAND_BOARD}
    static let rule: CGFloat = ${D.RULE}
    static let hairline: CGFloat = ${D.HAIRLINE}
    static let coverKeyline: CGFloat = ${D.COVER_KEYLINE}

    enum Cover {
        static let minW: CGFloat = ${D.cover.minW}
        static let heights: [CGFloat] = [${D.cover.heights.join(", ")}]
        static let comps = ${D.cover.comps}
        static let pad: CGFloat = ${D.cover.pad}
        static let jacketGlyph: CGFloat = ${D.JACKET_GLYPH}
        static let capsGlyph: CGFloat = ${D.CAPS_GLYPH}
        static let capsTracking: CGFloat = ${D.CAPS_TRACKING}
        static let quoteGlyph: CGFloat = ${D.QUOTE_GLYPH}
        static let quoteLeading: CGFloat = ${D.QUOTE_LEADING}
        static let emptyBoardH: CGFloat = ${D.EMPTY_BOARD_H}
        static let maxEmptyBoards = ${D.MAX_EMPTY_BOARDS}
    }

    static let placeholderMix: Double = ${D.PLACEHOLDER_MIX}

    /// Milliseconds.
    enum Duration {
${Object.entries(D.duration).map(([k, v]) => `        static let ${k}: Double = ${v}`).join("\n")}
    }

    /// Stiffness and damping DERIVED in design.js from a damping ratio and a
    /// settle time; nobody picks a stiffness.
    enum Spring {
${Object.entries(D.springs).map(([k, v]) => `        static let ${k} = (stiffness: ${num(v.stiffness)}, damping: ${num(v.damping)}, mass: ${num(v.mass ?? 1)})`).join("\n")}
    }

    static let staggerStep: Double = ${D.STAGGER_STEP}
    static let staggerMaxSteps = ${D.STAGGER_MAX_STEPS}
}
`;
writeFileSync(out, swift);
console.log(`wrote ${out}`);
