// DesignConstants.swift — GENERATED by tools/golden/design.mjs from app/src/design.js.
// Do not edit. Change design.js and run `node swift/tools/golden/design.mjs`.
//
// WHY THIS IS NOT Tokens.swift: that file lives in the app target and imports
// SwiftUI, and Core is Foundation only. These are the numbers the FUNCTIONS in
// design.js read (DesignMath.swift), and the palettes as the hex strings
// `mix`, `contrast` and the export page are written in. Same source, same
// generator rule: never typed by hand. DesignMathTests fails when this file is
// not what the generator writes.
import Foundation

enum DesignConstants {
    struct Step: Sendable, Equatable {
        let fontSize: Double
        let lineHeight: Double
        let letterSpacing: Double
        let fontWeight: String
    }

    static let typeFloor: Double = 11
    static let display = Step(fontSize: 36, lineHeight: 42, letterSpacing: -0.45, fontWeight: "700")
    static let title = Step(fontSize: 25.5, lineHeight: 29.5, letterSpacing: -0.28, fontWeight: "700")
    static let heading = Step(fontSize: 19.5, lineHeight: 25, letterSpacing: -0.14, fontWeight: "600")
    static let read = Step(fontSize: 17, lineHeight: 25, letterSpacing: -0.07, fontWeight: "400")
    static let body = Step(fontSize: 15, lineHeight: 22, letterSpacing: 0, fontWeight: "400")
    static let bodyMed = Step(fontSize: 15, lineHeight: 22, letterSpacing: 0, fontWeight: "600")
    static let meta = Step(fontSize: 12.5, lineHeight: 17.5, letterSpacing: 0.09, fontWeight: "400")
    static let micro = Step(fontSize: 11, lineHeight: 15, letterSpacing: 0.48, fontWeight: "600")
    static let type: [String: Step] = ["display": display, "title": title, "heading": heading, "read": read, "body": body, "bodyMed": bodyMed, "meta": meta, "micro": micro]

    static let sp: [String: Double] = ["xs": 4, "sm": 8, "md": 12, "lg": 16, "xl": 24, "xxl": 32, "huge": 48]
    enum Space {
        static let xs: Double = 4
        static let sm: Double = 8
        static let md: Double = 12
        static let lg: Double = 16
        static let xl: Double = 24
        static let xxl: Double = 32
        static let huge: Double = 48
    }

    static let board: Double = 7
    static let rule: Double = 3
    static let hairline: Double = 1
    static let coverKeyline: Double = 2

    static let coverMinW: Double = 104
    static let coverHeights: [Double] = [156, 164, 172]
    static let coverComps = 3
    static let coverPad: Double = 8
    static let emptyBoardH: Double = 88
    static let maxEmptyBoards = 4

    static let jacketGlyph: Double = 0.64
    static let capsGlyph: Double = 0.72
    static let capsTracking: Double = -0.048
    static let quoteGlyph: Double = 0.52
    static let quoteLeading: Double = 1.22

    static let placeholderMix: Double = 0.26
    static let staggerStep: Double = 32
    static let staggerMaxSteps = 8

    /// Every shelf, in shelf order, with `unsorted` (the pile) last.
    static let listKeys: [String] = ["books", "restaurants", "movies", "recipes", "quotes", "places", "wishlist", "notes", "unsorted"]
    /// The label colour a filled shelf names for itself. Notes is not here on
    /// purpose: ask `DesignMath.onFor`.
    static let listOn: [String: String] = [
        "books": "#FFFFFF",
        "restaurants": "#FFFFFF",
        "movies": "#0A0A0A",
        "recipes": "#FFFFFF",
        "quotes": "#FFFFFF",
        "places": "#FFFFFF",
        "wishlist": "#FFFFFF",
        "unsorted": "#FFFFFF",
    ]
    static let light: [String: String] = [
        "bg": "#FFFFFF",
        "surface": "#FFFFFF",
        "surfaceSunk": "#F2F2F2",
        "placeholder": "#EAEAEA",
        "ink": "#0A0A0A",
        "inkSoft": "#565656",
        "inkFaint": "#6E6E6E",
        "line": "#DADADA",
        "lineStrong": "#0A0A0A",
        "accent": "#E01000",
        "accentInk": "#FFFFFF",
        "good": "#007A3D",
        "warn": "#8A6100",
        "books": "#0B3EE3",
        "restaurants": "#E01000",
        "movies": "#FFD400",
        "recipes": "#007A3D",
        "quotes": "#6D28D9",
        "places": "#C2410C",
        "wishlist": "#D4107A",
        "notes": "#FFFFFF",
        "unsorted": "#6E6E6E",
        "onList": "#FFFFFF",
    ]
    static let dark: [String: String] = [
        "bg": "#0A0A0A",
        "surface": "#0A0A0A",
        "surfaceSunk": "#161616",
        "placeholder": "#1E1E1E",
        "ink": "#FFFFFF",
        "inkSoft": "#A8A8A8",
        "inkFaint": "#8A8A8A",
        "line": "#2C2C2C",
        "lineStrong": "#FFFFFF",
        "accent": "#FF5A45",
        "accentInk": "#0A0A0A",
        "good": "#00C462",
        "warn": "#E0B057",
        "books": "#0B3EE3",
        "restaurants": "#E01000",
        "movies": "#FFD400",
        "recipes": "#007A3D",
        "quotes": "#6D28D9",
        "places": "#C2410C",
        "wishlist": "#D4107A",
        "notes": "#0A0A0A",
        "unsorted": "#6E6E6E",
        "onList": "#FFFFFF",
    ]
}
